# Application launcher configuration

# Set application launcher
# Note: pass the final command to swaymsg so that the resulting window can be opened
# on the original workspace that the command was run on.
set $menu rofi -show drun | xargs swaymsg exec --

# Launcher keybinding
bindsym $mod+d exec $menu

# Application launcher styling
for_window [app_id="rofi"] {
    border none
    floating enable
}

