# Output configuration
output * scale 1.25
output eDP-1 scale 2.0

# Example manual configuration (uncomment and adjust as needed)
# output eDP-1 resolution 1920x1080 position 0,0
# output HDMI-A-1 resolution 1920x1080 position 1920,0

# Wallpaper configuration

output * background $wallpaper fill
client.focused $color0 $background $foreground $color7 $background
